import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const cardWidth = (width - 60) / 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6EEDF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  appName: { color: "#3F2C1C", fontSize: 20, fontWeight: "bold" },
  userEmail: { color: "#8B7355", fontSize: 11 },

  titleSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 15,
  },
  mainTitle: { color: "#3F2C1C", fontSize: 26, fontWeight: "bold" },
  statsText: { color: "#8B7355", fontSize: 13, marginTop: 4 },

  btnCreateWrapper: {
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 8,
  },
  btnCreate: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 18,
  },
  btnCreateText: { color: "#FFF8ED", fontWeight: "bold", marginLeft: 6 },

  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF8ED",
    marginHorizontal: 20,
    marginTop: 25,
    marginBottom: 20,
    paddingHorizontal: 15,
    height: 50,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  searchInput: { flex: 1, color: "#3F2C1C", marginLeft: 10 },

  row: {
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  noteCard: {
    width: cardWidth,
    borderRadius: 22,
    padding: 15,
    marginBottom: 20,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EADBC8",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  typeText: { fontSize: 10, color: "#5C4033", marginLeft: 4, fontWeight: "600" },
  actionIcons: { flexDirection: "row", gap: 6 },
  iconCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#EADBC8",
    justifyContent: "center",
    alignItems: "center",
  },
  noteTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#3F2C1C",
    marginBottom: 6,
  },
  noteContent: { fontSize: 13, color: "#5C4033", lineHeight: 18 },
  cardFooter: {
    marginTop: 15,
    borderTopWidth: 0.5,
    borderTopColor: "#EADBC8",
    paddingTop: 10,
  },
  noteDate: { fontSize: 11, color: "#8B7355", fontWeight: "600" },
  detailText: {
    fontSize: 10,
    color: "#8B7355",
    marginTop: 8,
    textAlign: "center",
  },

  bottomTabWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    justifyContent: "flex-end",
    zIndex: 30,
  },
  bottomTabBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 100,
    backgroundColor: "rgba(246, 237, 223, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
  },

  bottomTab: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 76,
    backgroundColor: "rgba(255,248,237,0.98)",
    borderRadius: 28,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EADBC8",
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
    zIndex: 20,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 54,
  },
  tabItemActive: {
    backgroundColor: "#6F4E37",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  tabLabel: { fontSize: 10, marginTop: 4, color: "#8B7355" },
});
