import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6EEDF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  appName: { color: "#3F2C1C", fontSize: 20, fontWeight: "bold" },
  userEmail: { color: "#8B7355", fontSize: 11 },
  titleSection: {
    paddingHorizontal: 20,
    marginTop: 15,
  },
  mainTitle: { color: "#3F2C1C", fontSize: 26, fontWeight: "bold" },
  statsText: { color: "#8B7355", fontSize: 13, marginTop: 6 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF8ED",
    marginHorizontal: 20,
    marginTop: 22,
    marginBottom: 16,
    paddingHorizontal: 15,
    height: 50,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  searchInput: {
    flex: 1,
    color: "#3F2C1C",
    marginLeft: 10,
  },
  deleteAllBtn: {
    alignSelf: "flex-end",
    marginRight: 20,
    marginBottom: 10,
    backgroundColor: "#6F4E37",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  deleteAllText: {
    color: "#FFF8ED",
    fontWeight: "700",
    marginLeft: 8,
    fontSize: 13,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 130,
  },
  card: {
    backgroundColor: "#FFF8ED",
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  cardTitle: {
    color: "#3F2C1C",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 6,
  },
  cardContent: {
    color: "#5C4033",
    fontSize: 12,
    lineHeight: 17,
  },
  cardMeta: {
    color: "#8B7355",
    fontSize: 11,
    marginTop: 10,
  },
  cardActions: {
    flexDirection: "row",
    marginTop: 12,
    alignItems: "center",
  },
  restoreBtn: {
    flex: 1,
    backgroundColor: "#6F4E37",
    borderRadius: 12,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  restoreText: {
    color: "#FFF8ED",
    fontWeight: "800",
    marginLeft: 6,
    fontSize: 13,
  },
  deleteBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#C45A4A",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  emptyState: {
    minHeight: 360,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  emptyIconWrap: {
    width: 90,
    height: 90,
    borderRadius: 24,
    backgroundColor: "#EADBC8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#3F2C1C",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  emptyText: {
    color: "#8B7355",
    textAlign: "center",
    fontSize: 13,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(63,44,28,0.32)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#FFF8ED",
    borderRadius: 22,
    padding: 22,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  modalIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#EADBC8",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 14,
  },
  modalTitle: {
    color: "#3F2C1C",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  modalText: {
    color: "#8B7355",
    textAlign: "center",
    marginTop: 10,
    lineHeight: 19,
    fontSize: 13,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  modalCancel: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EADBC8",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelText: {
    color: "#5C4033",
    fontWeight: "700",
  },
  modalConfirm: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#6F4E37",
    alignItems: "center",
    justifyContent: "center",
  },
  modalConfirmText: {
    color: "#FFF8ED",
    fontWeight: "800",
  },

  bottomTabWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    justifyContent: "flex-end",
    zIndex: 30,
  },
  bottomTabBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 100,
    backgroundColor: "rgba(246, 237, 223, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
  },
  bottomTab: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 76,
    backgroundColor: "rgba(255,248,237,0.98)",
    borderRadius: 28,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EADBC8",
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
    zIndex: 20,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 54,
  },
  tabItemActive: {
    backgroundColor: "#6F4E37",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  tabLabel: { fontSize: 10, marginTop: 4, color: "#8B7355" },
});