import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6EEDF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  brandRow: { flexDirection: "row", alignItems: "center" },
  brandIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  appName: { color: "#3F2C1C", fontSize: 18, fontWeight: "800" },
  userEmailSmall: { color: "#8B7355", fontSize: 10 },
  switchPill: {
    width: 54,
    height: 26,
    borderRadius: 999,
    backgroundColor: "#EADBC8",
    padding: 2,
    justifyContent: "center",
  },
  switchKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FFF8ED",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
  },
  pageLabel: {
    paddingHorizontal: 20,
    color: "#8B7355",
    fontSize: 12,
    marginTop: 8,
    marginBottom: 4,
  },
  title: {
    paddingHorizontal: 20,
    color: "#3F2C1C",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 18,
  },
  profileCard: {
    marginHorizontal: 20,
    borderRadius: 22,
    backgroundColor: "#FFF8ED",
    borderWidth: 1,
    borderColor: "#EADBC8",
    padding: 18,
    shadowColor: "#6F4E37",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  profileTop: { flexDirection: "row", alignItems: "center" },
  avatarFrame: {
    width: 66,
    height: 66,
    marginRight: 14,
  },
  avatarWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  cameraBadge: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 27,
    height: 27,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFF8ED",
  },
  nameRow: { flexDirection: "row", alignItems: "center" },
  username: {
    color: "#3F2C1C",
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
  },
  smallActionBtn: {
    backgroundColor: "#EADBC8",
    borderWidth: 1,
    borderColor: "#D8C0A3",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  smallActionText: {
    color: "#6F4E37",
    fontSize: 10,
    fontWeight: "700",
  },
  useremail: {
    marginTop: 4,
    fontSize: 11,
    color: "#8B7355",
  },
  form: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
    paddingTop: 14,
  },
  fieldGroup: { marginTop: 12 },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: "#8B7355",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#FFF8ED",
    borderRadius: 14,
    paddingHorizontal: 15,
    height: 54,
    fontSize: 15,
    color: "#3F2C1C",
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  disabledInput: {
    opacity: 0.7,
  },
  languageSelect: {
    minHeight: 54,
    borderRadius: 14,
    paddingHorizontal: 15,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  languageSelectText: {
    fontSize: 15,
    fontWeight: "700",
  },
  languageMenu: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
  },
  languageOption: {
    minHeight: 46,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  languageOptionText: {
    fontSize: 14,
    fontWeight: "700",
  },
  saveBtn: {
    height: 54,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 18,
    overflow: "hidden",
  },
  saveGradient: {
    flex: 1,
    width: "100%",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  saveText: {
    color: "#FFF8ED",
    fontSize: 16,
    fontWeight: "800",
    marginLeft: 8,
  },
  logoutBtn: {
    marginTop: 14,
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#C45A4A",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(196,90,74,0.08)",
  },
  logoutText: {
    color: "#C45A4A",
    fontSize: 15,
    fontWeight: "700",
  },
  bottomTabWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    justifyContent: "flex-end",
    zIndex: 30,
  },
  bottomTabBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 100,
    backgroundColor: "rgba(246, 237, 223, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
  },
  bottomTab: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 76,
    backgroundColor: "rgba(255,248,237,0.98)",
    borderRadius: 28,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EADBC8",
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
    zIndex: 20,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 54,
  },
  tabItemActive: {
    backgroundColor: "#6F4E37",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  tabLabel: { fontSize: 10, marginTop: 4, color: "#8B7355" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(63,44,28,0.32)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#FFF8ED",
    borderRadius: 22,
    padding: 22,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  modalIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#EADBC8",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 14,
  },
  modalTitle: {
    color: "#3F2C1C",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  modalText: {
    color: "#8B7355",
    textAlign: "center",
    marginTop: 10,
    lineHeight: 19,
    fontSize: 13,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  modalCancel: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EADBC8",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelText: {
    color: "#5C4033",
    fontWeight: "700",
  },
  modalConfirm: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#6F4E37",
    alignItems: "center",
    justifyContent: "center",
  },
  modalConfirmText: {
    color: "#FFF8ED",
    fontWeight: "800",
  },
});
