import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  toolbar: {
    minHeight: 74,
    borderBottomWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  toolbarTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  toolbarTitle: {
    fontSize: 17,
    fontWeight: "800",
    padding: 0,
    minHeight: 24,
  },
  toolbarMeta: {
    fontSize: 11,
    marginTop: 3,
  },
  toolbarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  visibilityPill: {
    minHeight: 38,
    borderRadius: 18,
    paddingLeft: 10,
    paddingRight: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  visibilityText: {
    fontSize: 12,
    fontWeight: "800",
  },
  saveButton: {
    height: 38,
    borderRadius: 18,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  saveText: {
    fontSize: 13,
    fontWeight: "800",
  },
  errorBar: {
    minHeight: 38,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: "#ff6b6b",
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  noticeBar: {
    minHeight: 38,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noticeText: {
    fontSize: 12,
    fontWeight: "600",
    flex: 1,
  },
  inviteBar: {
    minHeight: 48,
    paddingHorizontal: 18,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  inviteCopy: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inviteText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
  },
  inviteButton: {
    minHeight: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  inviteButtonText: {
    fontSize: 12,
    fontWeight: "800",
  },
  documentWrap: {
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 70,
  },
  documentPage: {
    width: "100%",
    minHeight: 720,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 34,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 5,
  },
  loader: {
    marginTop: 80,
  },
  documentBody: {
    minHeight: 640,
    fontSize: 17,
    lineHeight: 28,
    padding: 0,
    textAlignVertical: "top",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  inviteModal: {
    width: "100%",
    maxWidth: 420,
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  guestListBlock: {
    marginBottom: 16,
  },
  guestListHeader: {
    minHeight: 26,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 8,
  },
  guestListTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  guestList: {
    gap: 8,
    maxHeight: 190,
  },
  guestRow: {
    minHeight: 58,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  guestInfo: {
    flex: 1,
    minWidth: 0,
  },
  guestName: {
    fontSize: 13,
    fontWeight: "800",
  },
  guestEmail: {
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  guestPermission: {
    fontSize: 11,
    fontWeight: "700",
    marginTop: 3,
  },
  kickButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyGuestsText: {
    fontSize: 12,
    fontWeight: "600",
  },
  inviteInput: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    marginBottom: 14,
  },
  permissionRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  permissionTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  permissionTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  permissionHint: {
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  inviteStatus: {
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
  },
  modalInviteButton: {
    minHeight: 46,
    borderRadius: 23,
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  modalInviteText: {
    fontSize: 14,
    fontWeight: "800",
  },
});
