import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F6EEDF" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  appName: { color: "#3F2C1C", fontSize: 22, fontWeight: "bold" },
  userEmail: { color: "#8B7355", fontSize: 12 },
  titleSection: { paddingHorizontal: 20, marginTop: 20, marginBottom: 25 },
  mainTitle: { color: "#3F2C1C", fontSize: 28, fontWeight: "bold" },
  statsText: { color: "#8B7355", fontSize: 14, marginTop: 5 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF8ED",
    marginHorizontal: 20,
    paddingHorizontal: 15,
    height: 50,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#EADBC8",
    marginBottom: 25,
  },
  searchInput: { flex: 1, color: "#3F2C1C", marginLeft: 10 },

  sharedCard: {
    width: "100%",
    borderRadius: 25,
    padding: 20,
    marginBottom: 20,
    elevation: 5,
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: "#EADBC8",
  },
  cardHeader: { alignItems: "flex-end", marginBottom: 5 },
  actionIcons: { flexDirection: "row", gap: 10 },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EADBC8",
    justifyContent: "center",
    alignItems: "center",
  },
  noteTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3F2C1C",
    marginBottom: 10,
  },
  noteContent: {
    fontSize: 14,
    color: "#5C4033",
    lineHeight: 20,
    marginBottom: 15,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
    paddingTop: 10,
  },
  permissionBadge: { flexDirection: "row", alignItems: "center" },
  ownerName: { fontSize: 14, fontWeight: "bold", color: "#3F2C1C" },
  footerText: { fontSize: 12, color: "#8B7355" },
  clickDetail: {
    fontSize: 11,
    color: "#8B7355",
    textAlign: "center",
    marginTop: 12,
  },

  bottomTabWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    justifyContent: "flex-end",
    zIndex: 30,
  },
  bottomTabBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 100,
    backgroundColor: "rgba(246, 237, 223, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#EADBC8",
  },

  bottomTab: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 76,
    backgroundColor: "rgba(255,248,237,0.98)",
    borderRadius: 28,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EADBC8",
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
    zIndex: 20,
  },
  tabItem: {
    alignItems: "center",
    padding: 10,
    minWidth: 54,
  },
  tabItemActive: {
    backgroundColor: "#6F4E37",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: "#6F4E37",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  tabLabel: { fontSize: 10, marginTop: 4, color: "#8B7355" },
});
