import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#08081a" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  appName: { color: "#fff", fontSize: 22, fontWeight: "bold" },
  userEmail: { color: "rgba(255,255,255,0.5)", fontSize: 12 },
  titleSection: { paddingHorizontal: 20, marginTop: 20, marginBottom: 25 },
  mainTitle: { color: "#fff", fontSize: 28, fontWeight: "bold" },
  statsText: { color: "rgba(255,255,255,0.5)", fontSize: 14, marginTop: 5 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    marginHorizontal: 20,
    paddingHorizontal: 15,
    height: 50,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginBottom: 25,
  },
  searchInput: { flex: 1, color: "#fff", marginLeft: 10 },

  sharedCard: {
    width: "100%",
    borderRadius: 25,
    padding: 20,
    marginBottom: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  cardHeader: { alignItems: "flex-end", marginBottom: 5 },
  actionIcons: { flexDirection: "row", gap: 10 },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  noteTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#222",
    marginBottom: 10,
  },
  noteContent: {
    fontSize: 14,
    color: "#444",
    lineHeight: 20,
    marginBottom: 15,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 10,
  },
  permissionBadge: { flexDirection: "row", alignItems: "center" },
  ownerName: { fontSize: 14, fontWeight: "bold", color: "#222" },
  footerText: { fontSize: 12, color: "#444" },
  clickDetail: {
    fontSize: 11,
    color: "rgba(0,0,0,0.3)",
    textAlign: "center",
    marginTop: 12,
  },

  bottomTab: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    height: 75,
    backgroundColor: "rgba(20, 20, 45, 0.95)",
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  tabItem: { alignItems: "center", padding: 10 },
  tabItemActive: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 18,
    paddingHorizontal: 15,
  },
  tabLabel: { fontSize: 10, marginTop: 4, color: "rgba(255,255,255,0.4)" },
});
